### ISSUE TITLE
Could not generate temp file

### ISSUE THREAD

**Issue by egorovd** [arangodb/foxx-cli#41]
Hello.
There is a cluster of three servers (v3.6.1).
Everything is configured and everything works.
But when I try to add a fox-app, I get an error.

```json
{
 "code":500,
 "error":true,
 "errorMessage":"could not generate temp file: failed to create directory '/tmp/arangod_NFLJap/uploads': Permission denied",
 "errorNum":4
}
```

All services are launched like this:

```shell
/usr/sbin/arangod --uid arangodb --gid arangodb --pid-file /var/run/arangodb3/agency.pid
/usr/sbin/arangod --uid arangodb --gid arangodb --pid-file /var/run/arangodb3/dbserver.pid
/usr/sbin/arangod --uid arangodb --gid arangodb --pid-file /var/run/arangodb3/coordinator.pid
```
but a directory is created with such rights:

```shell
ls -l /tmp | grep NFLJa
drwx------ 2 root          root               4096 Apr 12 21:29 arangod_NFLJap/
```

How is this possible?
Maybe I have errors in the settings?

Thank you.

**Comment by pluma** [comment]
This looks like an issue with ArangoDB, not foxx-cli. I'm closing this as there's nothing that can be done from this end and it's been a while since you reported this issue. If you are still seeing this problem, please open an issue with the main arangodb repository or ask on the community slack: https://slack.arangodb.com
